In [105]:
from wyckoff_transformer.tokenization import load_tensors_and_tokenisers

tensors, tokenisers, token_engineers = load_tensors_and_tokenisers("matbench_discovery", "sg_scalars")

In [111]:
len(tensors['train']['site_symmetries'])

145923

In [112]:
len(tensors['val']['site_symmetries'])

256963

In [1]:
from pyxtal import Group

In [28]:
g = Group(162)

In [102]:
import numpy as np
def check_group(group_number):
    group = Group(group_number)
    last_site_symmetry = None
    last_distace = None
    for wyckoff_position in group:
        wyckoff_position.get_site_symmetry()
        this_distance = np.linalg.norm(wyckoff_position.ops[0].affine_matrix[:3, 3])
        print(wyckoff_position.site_symm, this_distance)
        if wyckoff_position.site_symm == last_site_symmetry:
            if this_distance > last_distance:
                print(f"Group {group_number} has a Wyckoff position with site symmetry {wyckoff_position.site_symm} that is not ordered by distance")
        last_site_symmetry = wyckoff_position.site_symm
        last_distance = this_distance

In [ ]:
for i in range(1, 231):
    check_group(i)

1 0.0
1 0.0
-1 0.8660254037844386
-1 0.7071067811865476
-1 0.7071067811865476
-1 0.7071067811865476
-1 0.5
-1 0.5
-1 0.5
-1 0.0
1 0.0
2 0.7071067811865476
2 0.5
2 0.5
2 0.0
1 0.0
1 0.0
2 0.5
2 0.0
1 0.0
m 0.5
m 0.0
1 0.0
1 0.0
m 0.0
1 0.0
1 0.0
m 0.5
m 0.0
2 0.7071067811865476
2 0.5
2 0.5
2 0.0
2/m 0.8660254037844386
2/m 0.7071067811865476
2/m 0.7071067811865476
2/m 0.7071067811865476
2/m 0.5
2/m 0.5
2/m 0.5
2/m 0.0
1 0.0
m 0.25
-1 0.7071067811865476
-1 0.5
-1 0.5
-1 0.0
1 0.0
m 0.0
2 0.5
2 0.0
-1 0.6123724356957945
-1 0.3535533905932738
2/m 0.7071067811865476
2/m 0.5
2/m 0.5
2/m 0.0
1 0.0
2 0.5590169943749475
2 0.25
-1 0.5
-1 0.5
-1 0.7071067811865476
Group 13 has a Wyckoff position with site symmetry -1 that is not ordered by distance
-1 0.0
1 0.0
-1 0.7071067811865476
-1 0.5
-1 0.5
-1 0.0
1 0.0
2 0.25
-1 0.6123724356957945
-1 0.3535533905932738
-1 0.5
Group 15 has a Wyckoff position with site symmetry -1 that is not ordered by distance
-1 0.0
1 0.0
..2 0.7071067811865476
..2 0.5
..2

In [96]:
Group(13)[-1].ops[0].affine_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [101]:
Group(13)[-2].ops[1].affine_matrix

array([[0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 1. ]])

In [98]:
Group(13)[-3].ops[0].affine_matrix

array([[0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. ]])

In [100]:
Group(13)

-- Spacegroup --# 13 (P2/c)--
4g	site symm: 1
2f	site symm: 2
2e	site symm: 2
2d	site symm: -1
2c	site symm: -1
2b	site symm: -1
2a	site symm: -1

In [89]:
Group(13)[7]

IndexError: list index out of range

In [38]:
g[3].ops[0].affine_matrix

array([[ 1.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [34]:
g[2].ops

[SymmOp(self.affine_matrix=array([[ 1. ,  0. ,  0. ,  0. ],
        [-1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[1. , 0. , 0. , 0. ],
        [2. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]])),
 SymmOp(self.affine_matrix=array([[-2. ,  0. ,  0. ,  0. ],
        [-1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[-1. ,  0. ,  0. ,  0. ],
        [ 1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[-1. ,  0. ,  0. ,  0. ],
        [-2. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[2. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]]))]

In [27]:
s.ops[0]

SymmOp(self.affine_matrix=array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))

In [25]:
g[-2].get_euclidean_generator()

TypeError: Wyckoff_position.get_euclidean_generator() missing 1 required positional argument: 'cell'

In [18]:
s.project((1,1,1))

array([0., 0., 0.])

In [101]:
s.ops

[SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]])),
 SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]]))]

In [103]:
g[-2].ops

[SymmOp(self.affine_matrix=array([[0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]]))]

In [104]:
g[-1].ops

[SymmOp(self.affine_matrix=array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.]]))]

In [62]:
g[-3].ops

[SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        ]])),
 SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        ]]))]

In [ ]:
g[-4].

[SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]])),
 SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]]))]

In [39]:
g[-2].get_site_symmetry_object().to_one_hot()

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
g

-- Spacegroup --# 150 (P321)--
6g	site symm: 1
3f	site symm: 1
3e	site symm: 1
2d	site symm: 3..
2c	site symm: 3..
1b	site symm: 32.
1a	site symm: 32.