In [3]:
from mp_20_utils import load_all_data
from tokenization import MASK_SITE
import torch
device = 'cpu'
datasets_pd, torch_datasets, site_to_ids, element_to_ids, spacegroup_to_ids, max_len = load_all_data(
    device=device, allow_retokenize=False)

In [4]:
import numpy as np
for dataset in datasets_pd.values():
    lattices = map(lambda s: s.get_primitive_structure().lattice, dataset['structure'])
    dataset['lattice'] = list(lattices)
    dataset['volume'] = [l.volume for l in dataset['lattice']]
    dataset['abc'] = [np.array(l.abc) for l in dataset['lattice']]
    dataset['angles'] = [np.array(l.angles) for l in dataset['lattice']]

In [5]:
# Is abc sorted?
tol = 1e-1
for dataset in datasets_pd.values():
    abc = dataset['abc']
    for row in abc:
        print(row)
        assert np.all(row[:-1] <= row[1:] + tol)

[3.029284   5.63711369 7.97762755]
[5.199118  6.8098636 6.8098636]
[4.16442336 4.16442336 4.16442336]
[ 3.858783  5.345396 12.343091]
[7.58418904 7.58418904 7.58418904]
[4.299534   8.15825496 8.15825496]
[3.403761  8.418362  8.4183617]
[5.9525281  5.98276482 5.98276482]
[3.935757   6.67033    9.94385815]
[4.004424   4.89161618 4.89161618]
[6.39789338 7.75471327 7.83032765]
[ 4.336205  4.498197 13.031643]
[ 4.51431     4.51430988 10.284149  ]
[3.15302   3.1530205 5.124253 ]
[8.51144998 8.51144998 8.51144998]
[4.251552  4.251552  5.8284391]
[4.48471    4.48471018 7.381589  ]
[5.47517047 5.47517047 6.97041317]
[4.57798608 4.57798608 4.57798608]
[5.397527 5.397527 7.454301]
[3.270839   5.741837   6.47423013]
[4.15647407 4.15647407 4.15647407]
[3.25967    5.178714   8.45343521]
[4.772748   5.649399   5.65908464]
[4.753226   4.75322646 5.641794  ]
[4.334384   7.223096   7.22309545]
[6.60952649 6.60952649 6.60952649]
[5.60984294 5.77462    8.07235025]
[6.35920798 6.35920798 6.94430231]
[4.631

AssertionError: 

In [ ]:
l = datasets_pd['train'].lattice.iloc[0]

In [ ]:
from pyxtal import pyxtal

In [7]:
pyxtal_structure = pyxtal()
pyxtal_structure.from_seed(datasets_pd['train'].structure.iloc[0])

In [10]:
l = pyxtal_structure.lattice

In [12]:
l.volume

254.63066551847865

In [15]:
l.matrix

array([[ 1.49112455e+01,  1.25317586e-15, -4.80087095e+00],
       [ 0.00000000e+00,  3.02928400e+00,  1.85490148e-16],
       [ 0.00000000e+00,  0.00000000e+00,  5.63711369e+00]])

In [17]:
l.ltype

'monoclinic'

In [11]:
(data_element, target_element), (data_site, target_site) = get_batches(
    ds['symmetry_elements'],
    ds['symmetry_elements'],
    3,
    torch.tensor(site_to_ids[MASK_SITE]).to(device)
)

In [18]:
data_element['species'].shape

torch.Size([27136, 3])

In [20]:
target_element.shape

torch.Size([27136])

In [18]:
a=[1,2,3]

In [19]:
a[:-1]

[1, 2]

In [24]:
target_site.shape

torch.Size([27136])