In [1]:
import pyxtal

In [2]:
g = pyxtal.Group(225)
w = g[4]

In [3]:
from pymatgen.core import Element

In [4]:
Element("Au").symbol

'Au'

In [5]:
w.get_site_symmetry()

In [8]:
w

Wyckoff position 48h in space group 225 with site symmetry m.m2
0, y, y
0, -y, y
0, y, -y
0, -y, -y
y, 0, y
y, 0, -y
-y, 0, y
-y, 0, -y
y, y, 0
-y, y, 0
y, -y, 0
-y, -y, 0
0, y+1/2, y+1/2
0, -y+1/2, y+1/2
0, y+1/2, -y+1/2
0, -y+1/2, -y+1/2
y, 1/2, y+1/2
y, 1/2, -y+1/2
-y, 1/2, y+1/2
-y, 1/2, -y+1/2
y, y+1/2, 1/2
-y, y+1/2, 1/2
y, -y+1/2, 1/2
-y, -y+1/2, 1/2
1/2, y, y+1/2
1/2, -y, y+1/2
1/2, y, -y+1/2
1/2, -y, -y+1/2
y+1/2, 0, y+1/2
y+1/2, 0, -y+1/2
-y+1/2, 0, y+1/2
-y+1/2, 0, -y+1/2
y+1/2, y, 1/2
-y+1/2, y, 1/2
y+1/2, -y, 1/2
-y+1/2, -y, 1/2
1/2, y+1/2, y
1/2, -y+1/2, y
1/2, y+1/2, -y
1/2, -y+1/2, -y
y+1/2, 1/2, y
y+1/2, 1/2, -y
-y+1/2, 1/2, y
-y+1/2, 1/2, -y
y+1/2, y+1/2, 0
-y+1/2, y+1/2, 0
y+1/2, -y+1/2, 0
-y+1/2, -y+1/2, 0

In [75]:
g2 = pyxtal.Group(2)
g2

-- Spacegroup --# 2 (P-1)--
2i	site symm: 1
1h	site symm: -1
1g	site symm: -1
1f	site symm: -1
1e	site symm: -1
1d	site symm: -1
1c	site symm: -1
1b	site symm: -1
1a	site symm: -1

In [76]:
(g.get_spg_symmetry_object().to_matrix_representation_spg() - g2.get_spg_symmetry_object().to_matrix_representation_spg()==0).sum()

358

In [12]:
set((g.get_spg_symmetry_object().to_matrix_representation_spg(), g.get_spg_symmetry_object().to_matrix_representation_spg()))

TypeError: unhashable type: 'numpy.ndarray'

In [33]:
all_spgs = []
for group_number in range(1, 231):
    g = pyxtal.Group(group_number)
    all_spgs.append(g.get_spg_symmetry_object().to_matrix_representation_spg().ravel())

In [35]:
all_spgs_sum = sum(all_spgs)
constant_indices = (all_spgs_sum == 0) | (all_spgs_sum == len(all_spgs))

In [38]:
constant_indices.sum()

284

In [39]:
len(constant_indices)

390

In [27]:
out.shape

(229, 390)

In [12]:
type(s)

pyxtal.symmetry.site_symmetry

In [8]:
r = s.to_matrix_representation()

In [13]:
s.to_one_hot()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
s.to_matrix_representation().shape

(15, 10)

In [26]:
s.get_name()
s.name

'1-122_1mabcnd33_13_24-44_14_24_3-366_16_26_36_46_5-6'

In [30]:
s.set_table()
type(s.table)

list

In [33]:
s.to_matrix_representation()

array([[1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
s.to_matrix_representation_spg()

array([[1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 