In [1]:
import pyxtal

In [40]:
pyxtal.Group(3)

-- Spacegroup --# 3 (P2)--
2e	site symm: 1
1d	site symm: 2
1c	site symm: 2
1b	site symm: 2
1a	site symm: 2

In [42]:
pyxtal.Group(5)

-- Spacegroup --# 5 (C2)--
4c	site symm: 1
2b	site symm: 2
2a	site symm: 2

In [49]:
pyxtal.Group(5).get_spg_symmetry_object() == pyxtal.Group(3).get_spg_symmetry_object() 

False

In [161]:
g1 = pyxtal.Group(21)
g2 = pyxtal.Group(23)

In [162]:
g1.cellsize()

2

In [163]:
g2.cellsize()

2

In [164]:
g1.symbol[0]

'C'

In [166]:
g2.symbol[0]

'I'

In [146]:
Group = pyxtal.Group

In [150]:
Group(23).cellsize()

2

In [154]:
Group(21).cellsize()

2

In [155]:
Group(23)

-- Spacegroup --# 23 (I222)--
8k	site symm: 1
4j	site symm: ..2
4i	site symm: ..2
4h	site symm: .2.
4g	site symm: .2.
4f	site symm: 2..
4e	site symm: 2..
2d	site symm: 222
2c	site symm: 222
2b	site symm: 222
2a	site symm: 222

In [157]:
Group(21)

-- Spacegroup --# 21 (C222)--
8l	site symm: 1
4k	site symm: ..2
4j	site symm: ..2
4i	site symm: ..2
4h	site symm: .2.
4g	site symm: .2.
4f	site symm: 2..
4e	site symm: 2..
2d	site symm: 222
2c	site symm: 222
2b	site symm: 222
2a	site symm: 222

In [159]:
Group(23).lattice_type

'orthorhombic'

In [160]:
Group(21).lattice_type

'orthorhombic'

In [167]:
(pyxtal.Group(21).get_spg_symmetry_object().to_one_hot()==pyxtal.Group(23).get_spg_symmetry_object().to_one_hot()).all()

True

In [168]:
symbols = ("P", "A", "C", "I", "R", "F")
symbol_to_number = {s: i for i, s in enumerate(symbols)}

In [174]:
symmetry_matrices = {}
grop_matrices = set()
wrong = 0
right = 0
for group_number in range(1, 231):
    group = pyxtal.Group(group_number)
    group_symmetry_object = group.get_spg_symmetry_object().to_matrix_representation_spg().ravel().tolist()
    group_symmetry_object.append(symbol_to_number[group.symbol[0]])
    group_symmetry_object = tuple(group_symmetry_object)
    if group_symmetry_object in grop_matrices:
        raise ValueError(f"Group {group_number} is already in the list")
    grop_matrices.add(group_symmetry_object)
    #print("Groups are all different")
    for wp in group.Wyckoff_positions:
        wp.get_site_symmetry()
        wp_symmetry_object= wp.get_site_symmetry_object()
        wp_matrix = wp_symmetry_object.to_matrix_representation()
        if wp.site_symm in symmetry_matrices:
            if (wp_matrix != symmetry_matrices[wp.site_symm]).any():
                #print("Group: ", group_number, "Wyckoff: ", wp.letter, "Symmetry: ", wp.site_symm)
                #print("Matrix: ", wp_matrix)
                #print("Old Matrix: ", symmetry_matrices[wp.site_symm])
                #break
                wrong += 1
            else:
                right += 1
        else:
            symmetry_matrices[wp.site_symm] = wp_matrix

In [4]:
print("Right: ", right)
print("Wrong: ", wrong)

Right:  776
Wrong:  0


In [5]:
symmetry_matrices[wp.site_symm]

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
wp_matrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
wp.get_site_symmetry_object().to_matrix_representation_spg()

To debug None ~~ Operation: -x+1/4, -z+1/4, -y+1/4 ~~
Type: rotation
Order: 2
Angle: 3.141592653589793
Axis: [ 0.          0.70710678 -0.70710678]


SystemExit: 

/home/kna/.cache/pypoetry/virtualenvs/wyckofftransformer-psWxdoGj-py3.10/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [8]:
from pymatgen.core import Element

In [9]:
Element("Au").symbol

'Au'

In [10]:
w.get_site_symmetry()

In [11]:
w

Wyckoff position 48h in space group 225 with site symmetry m.m2
0, y, y
0, -y, y
0, y, -y
0, -y, -y
y, 0, y
y, 0, -y
-y, 0, y
-y, 0, -y
y, y, 0
-y, y, 0
y, -y, 0
-y, -y, 0
0, y+1/2, y+1/2
0, -y+1/2, y+1/2
0, y+1/2, -y+1/2
0, -y+1/2, -y+1/2
y, 1/2, y+1/2
y, 1/2, -y+1/2
-y, 1/2, y+1/2
-y, 1/2, -y+1/2
y, y+1/2, 1/2
-y, y+1/2, 1/2
y, -y+1/2, 1/2
-y, -y+1/2, 1/2
1/2, y, y+1/2
1/2, -y, y+1/2
1/2, y, -y+1/2
1/2, -y, -y+1/2
y+1/2, 0, y+1/2
y+1/2, 0, -y+1/2
-y+1/2, 0, y+1/2
-y+1/2, 0, -y+1/2
y+1/2, y, 1/2
-y+1/2, y, 1/2
y+1/2, -y, 1/2
-y+1/2, -y, 1/2
1/2, y+1/2, y
1/2, -y+1/2, y
1/2, y+1/2, -y
1/2, -y+1/2, -y
y+1/2, 1/2, y
y+1/2, 1/2, -y
-y+1/2, 1/2, y
-y+1/2, 1/2, -y
y+1/2, y+1/2, 0
-y+1/2, y+1/2, 0
y+1/2, -y+1/2, 0
-y+1/2, -y+1/2, 0

In [12]:
g2 = pyxtal.Group(2)
g2

-- Spacegroup --# 2 (P-1)--
2i	site symm: 1
1h	site symm: -1
1g	site symm: -1
1f	site symm: -1
1e	site symm: -1
1d	site symm: -1
1c	site symm: -1
1b	site symm: -1
1a	site symm: -1

In [13]:
(g.get_spg_symmetry_object().to_matrix_representation_spg() - g2.get_spg_symmetry_object().to_matrix_representation_spg()==0).sum()

358

In [14]:
set((g.get_spg_symmetry_object().to_matrix_representation_spg(), g.get_spg_symmetry_object().to_matrix_representation_spg()))

TypeError: unhashable type: 'numpy.ndarray'

In [15]:
all_spgs = []
for group_number in range(1, 231):
    g = pyxtal.Group(group_number)
    all_spgs.append(g.get_spg_symmetry_object().to_matrix_representation_spg().ravel())

In [16]:
all_spgs_sum = sum(all_spgs)
constant_indices = (all_spgs_sum == 0) | (all_spgs_sum == len(all_spgs))

In [17]:
constant_indices.sum()

284

In [18]:
len(constant_indices)

390

In [19]:
out.shape

NameError: name 'out' is not defined

In [ ]:
type(s)

pyxtal.symmetry.site_symmetry

In [ ]:
r = s.to_matrix_representation()

In [ ]:
s.to_one_hot()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
s.to_matrix_representation().shape

(15, 10)

In [20]:
s.get_name()
s.name

NameError: name 's' is not defined

In [21]:
s.set_table()
type(s.table)

NameError: name 's' is not defined

In [22]:
s.to_matrix_representation()

NameError: name 's' is not defined

In [23]:
s.to_matrix_representation_spg()

NameError: name 's' is not defined